name: Auto Tag

on:
  push:
    branches:
      - main  # Cambiar por la rama que desees monitorear

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag
        run: git fetch --tags --depth=1

      - name: Determine new tag version
        id: determine_tag
        run: |
          # Obtenemos el último tag existente
          LAST_TAG=$(git describe --tags --abbrev=0)

          # Incrementamos la versión en el formato "vX.X.X"
          IFS='.' read -r -a VERSION_PARTS <<< "${LAST_TAG:1}"
          NEW_VERSION="v${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$((VERSION_PARTS[2]+1))"

          # Creamos el nuevo tag
          echo ::set-output name=NEW_TAG::$NEW_VERSION

      - name: Create and push new tag
        if: ${{ steps.determine_tag.outputs.NEW_TAG != '' }}
        run: |
          git tag ${{ steps.determine_tag.outputs.NEW_TAG }}
          git push origin ${{ steps.determine_tag.outputs.NEW_TAG }}
