name: Auto Tag

on:
  push:
    branches:
      - main  # Cambiar por la rama que desees monitorear

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag (if available)
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Determine new tag version
        id: determine_tag
        run: |
          # Obtenemos el último tag existente
          LAST_TAG=${{ env.TAG }}

          # Incrementamos la versión en el formato "vX.X.X"
          IFS='.' read -r -a VERSION_PARTS <<< "${LAST_TAG:1}"
          NEW_VERSION="v${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$((VERSION_PARTS[2]+1))"

          # Creamos el nuevo tag
          echo "NEW_TAG=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Create and push new tag
        if: ${{ env.NEW_TAG != '' }}
        run: |
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
